@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the Kisê User Manual.
@c Copyright (C)  2011 - 2016 Free Software Foundation, Inc.


@copying
This manual documents Kisê version @value{VERSION}.

Copyright (C) 2011 - 2016 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end copying


@node Introduction
@chapter Introduction

@menu
* About Kisê::
* Kisê the name::
* What else::
* Obtaining and Installing Kisê::
* Reporting Bugs::
@end menu


@c @unnumberedsec About Kisê
@node About Kisê
@section About Kisê

Kisê is a small and easy to use time keeping application.  It can be
used in a single user mode or by small organizations.  The fields it
handles are: a @strong{reference}, a @strong{date}, @strong{who},
@strong{for whom}, @strong{what}, a @strong{duration}, whether or not
the time keeping entry needs @strong{to be charged} and a
@strong{description}.  The reference is handled automatically by Kisê
and therefore is a @emph{read only} field.

A powerful dynamic filters criteria mechanism lets you visualize, work
on and print a subset of your time keeping entries.  Unlike most other
similar applications, this mechanism is available on Kisê's main
application window.

A printing templates system allows you to (pre)define, reuse and hence
quickly generate the pdf files and/or printed reports of your needs.

An import/export facility is under work for remote collaboration.

@node Kisê the name
@section Kisê the name

Kisê comes from the language @emph{Tupi-Guarani}.  It means 'an old
and/or rusty knife'.  It should be pronounced @samp{ki-c}.  However, if
you pronounce it @samp{kee-c}, it would come close to the french
expression 'qui sait?', which means 'who knows?'.  Then comes why the
name: 'qui sait? kisê!' - 'who knows?  Kisê!'.  Neat dont you think ?
Finally, this kind of application is (also) used to, in the end, produce
invoices, quite a pain, which could (too) well be caused by 'an old
and/or rusty knife'...

@node What else
@section What else

Kisê is written in @uref{@value{UGUILE}, guile}, an interpreter and
compiler for the @uref{@value{USCHEME}, scheme} programming language.
It uses @uref{@value{UGUILE-GNOME}, guile-gnome} for its graphical
interface, @uref{@value{USQLITE}, SQLite} for its database backend and
@uref{@value{ULATEX}, latex} for the reports.


@node Obtaining and Installing Kisê
@section Obtaining and Installing Kisê

Kisê can be obtained from the following archive site
@uref{@value{UKISE-RELEASES}}.  The file will be named
kise-version.tar.gz. The current version is @value{VERSION}, so the file
you should grab is:

@tie{}@tie{}@tie{}@tie{}@uref{@value{UKISE-LATEST}}

@menu
* Dependencies::
* Quickstart::
@end menu

@node Dependencies
@subsection Dependencies

Kisê needs the following software to run:

@itemize @bullet
@item
@uref{@value{UGUILE}, guile}>= 2.0.5
@item
@uref{@value{UGUILE-GNOME}, guile-gnome} >= 2.16.2
@item 
@uref{@value{USQLITE}, SQLite} >= 3.7
@item 
@uref{@value{USQLITE3-PCRE}, sqlite3-pcre}: perl compatible regular expression support for SQLite
@item
@uref{@value{ULATEX}, latex}: any recent latex 2e version will do
@end itemize

Kisê reports needs the following font:

@itemize @bullet
@item 
@uref{@value{UIWONA}, iwona}: on debian iwona is part of the
texlive-fonts-extra package
@end itemize


@node Quickstart
@subsection Quickstart

Assuming you have satisfied the dependencies, open a terminal and
proceed with the following steps:

@example
cd <download-path>
tar zxf kise-@value{VERSION}.tar.gz
cd kise-@value{VERSION}
./configure [--prefix=/your/prefix]
make
make install
@end example

To start Kisê:

@example
kise
@end example

@strong{Notes:}

@enumerate
@item
In the above @code{configure} step, @code{--prefix=/your/prefix} is
optional, as indicated by the presence of the @code{[]}.  The default
value is @code{/usr/local}.  As an example, you could use

@example
./configure --prefix=/opt
@end example

@item
To install Kisê, @code{make install}, you must have @code{write
permissions} for (a) @code{$prefix} and its subdirs, (b) the
@code{guile-gnome-2} and (c) guile's @code{site-ccache} dirs [see
below].

@item
Like for any other GNU Tool Chain compatible software, you may install
the documentation locally using @code{make install-html} [or @code{make
install-pdf} ...].

@item
Kisê's modules are installed in the @code{guile-gnome-2} directory.  If
you want to know its location, it is listed as part of the configure
step and stored in the config.log file, look for "checking for
guile-gnome-2"

@item
Kisê's compiled modules are installed in the Guile's @code{site-ccache}
directory.  If you want to know its location, enter the following
expression in a terminal:

@example
guile -c "(display (%site-ccache-dir)) (newline)"
@end example

@item
Unless already done, add @file{/usr/local/bin} or
@file{/your/prefix/bin} to the @code{PATH} variable of your default
shell configuration file.  As an example, using bash, you would add the
following line at the end of your .bashrc file [assuming --prefix=/opt]:

@example
export PATH=/opt/bin:$PATH
@end example
@end enumerate

Happy Kisê!


@node Reporting Bugs
@section Reporting Bugs

Please send your questions, bug reports and/or requests for improvements
to @email{david at altosw dot be}.
