@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Foliot User Manual.
@c Copyright (C)  2011 - 2018 Free Software Foundation, Inc.


@node Introduction
@chapter Introduction

@menu
* About GNU Foliot::
* The name::
* What else::
* Savannah::
* Obtaining and Installing GNU Foliot::
* Contact::
@end menu


@c @unnumberedsec About GNU Foliot
@node About GNU Foliot
@section About GNU Foliot

GNU Foliot is a small and easy to use time keeping application.

It can be used in a single user mode or by small organizations. Starting
with version 0.9.4, it can import other user's database, an essential
feature for remote collaborators.

The fields it handles are: a @strong{reference}, a @strong{date},
@strong{who}, @strong{for whom}, @strong{what}, a @strong{duration},
whether or not the time keeping entry needs @strong{to be charged} and a
@strong{description}.  The reference is handled automatically by GNU
Foliot and therefore is a @emph{read only} field.

It includes, on the main application screen, a powerful dynamic filters
criteria mechanism, which lets you visualize, work on and print a subset
of your time keeping entries.

A printing templates system allows you to (pre)define, reuse and hence
quickly generate the pdf files and/or printed reports of your needs.

A version which will let users export an active filter based subset of
their time keeping entries is under work.

@node The name
@section The name

Foliot was the name given, back in the 13th century, to one of the
essential components of the first all-mecanical clocks:

@quotation
... Starting in the 13th century, large tower clocks were built in
European town squares, cathedrals, and monasteries. They kept time by
using the verge escapement to drive a foliot, an horizontal bar with
weights on the ends, a primitive type of balance wheel, to oscillate
back and forth. The rate of the clock could be adjusted by sliding the
weights in or out on the foliot bar ...
@author @uref{@value{UFOLIOT-WIKIPEDIA}, Wikipedia}
@end quotation

@node What else
@section What else

GNU Foliot is written in @uref{@value{UGUILE}, Guile}, an
interpreter and compiler for the @uref{@value{USCHEME}, Scheme}
programming language.  It uses @uref{@value{UGUILE-GNOME}, Guile-Gnome}
for its graphical interface, @uref{@value{USQLITE}, SQLite} for its
database backend and @uref{@value{ULATEX}, LaTex} for the reports.


@node Savannah
@section Savannah

GNU Foliot also has a @uref{@value{UFOLIOT-SAVANNAH}, Savannah} project
page.

@node Obtaining and Installing GNU Foliot
@section Obtaining and Installing GNU Foliot

GNU Foliot can be obtained from the following archive site
@uref{@value{UFOLIOT-RELEASES}}.  The file will be named
foliot-version.tar.gz. The current version is @value{VERSION}, so the file
you should grab is:

@tie{}@tie{}@tie{}@tie{}@uref{@value{UFOLIOT-LATEST}}

@menu
* Dependencies::
* Quickstart::
@end menu

@node Dependencies
@subsection Dependencies

GNU Foliot needs the following software to run:

@itemize @bullet

@item
Autoconf >= 2.69

@item
Automake >= 1.14

@item
@uref{@value{UGUILE}, Guile}>= 2.0.14

@item
@uref{@value{UGUILE-GNOME}, Guile-Gnome} >= 2.16.5, the following
wrappers:

  @indentedblock
  Glib, Gobject, Pango, Pangocairo, libgnome, libgnomeui, libglade, Gtk
  @end indentedblock

@item 
@uref{@value{USQLITE}, SQLite} >= 3.7

@item
libpcre

@comment @item
@comment @uref{@value{USQLITE3-PCRE}, sqlite3-pcre}: perl compatible
@comment regular expression support for SQLite

@item
@uref{@value{UGRIP}, Grip} >= 0.1.2

  @indentedblock
  Grip (core), Grip-gnome, Grip-SQLite
  @end indentedblock

@item
@uref{@value{ULATEX}, LaTex}: any recent LaTex 2e version will do

@end itemize

GNU Foliot reports needs the following font:

@itemize @bullet
@item 
@uref{@value{UIWONA}, Iwona}: on debian iwona is part of the
texlive-fonts-extra package
@end itemize


@node Quickstart
@subsection Quickstart

Assuming you have satisfied the dependencies, open a terminal and
proceed with the following steps:

@example
cd <download-path>
tar zxf foliot-@value{VERSION}.tar.gz
cd foliot-@value{VERSION}
./configure [--prefix=/your/prefix]
make
make install
@end example

To start GNU Foliot, open a terminal and enter:

@example
foliot
@end example

Happy GNU Foliot!

@*
@strong{Notes:}

@enumerate
@item
In the above @code{configure} step, @code{--prefix=/your/prefix} is
optional.  The default value is @code{/usr/local}.  As an example, you
could use

@example
./configure --prefix=/opt
@end example

@item
To install GNU Foliot, @code{make install}, you must have @code{write
permissions} for (a) @code{$prefix} and its subdirs, (b) the
@code{guile-gnome-2} and (c) guile's @code{site-ccache} dirs [see
below].
@ifhtml
@*@*
@end ifhtml

@item
GNU Foliot's modules are installed in the @code{guile-gnome-2} directory.  If
you want to know its location, it is listed as part of the configure
step and stored in the config.log file, look for "checking for
guile-gnome-2"
@ifhtml
@*@*
@end ifhtml

@item
GNU Foliot's compiled modules are installed in the Guile's @code{site-ccache}
directory.  If you want to know its location, enter the following
expression in a terminal:

@example
guile -c "(display (%site-ccache-dir)) (newline)"
@end example

@item
Unless already done, add @file{/your/prefix/bin} to the @code{PATH}
variable of your default shell configuration file.  As an example, using
bash, you would add the following line at the end of your .bashrc file
[assuming --prefix=/opt]:

@example
export PATH=/opt/bin:$PATH
@end example

@item
Like for any other GNU Tool Chain compatible software, you may install
the documentation locally using @code{make install-html} [or @code{make
install-pdf} ...]. Note that as it is, GNU Foliot's documentation still
is a mock-up.

@end enumerate


@node Contact
@section Contact

@menu
* Mailing list::
* Reporting Bugs::
* IRC::
@end menu

@node Mailing list
@subsection Mailing list

GNU Foliot uses the following mailing list:

@itemize @bullet
@item foliot-user at gnu dot org
@end itemize

You can (un)subscribe to the list by following instructions on the
@uref{@value{UFOLIOT-LISTINFO}, list information page}.


@node Reporting Bugs
@subsection Reporting Bugs

GNU Foliot has a @uref{@value{UFOLIOT-BUGS-TRACKER}, bugs tracker}. You
may send your bugs report here:

@itemize @bullet
@item bug-foliot at gnu dot org
@end itemize

You can (un)subscribe to the bugs report list by following instructions
on the @uref{@value{UFOLIOT-BUGS-LISTINFO}, list information page}.


@node IRC
@subsection IRC

Most of the time you can find me on irc, channel @emph{#guile},
@emph{#guix} and @emph{#scheme} on @emph{irc.freenode.net},
@emph{#clutter} on @emph{irc.gnome.org}, under the nickname
@strong{daviid}.
