\input texinfo
@c -*-texinfo-*-
@documentencoding UTF-8
@c @paragraphindent none
@firstparagraphindent insert

@c start of header
@setfilename kise.info
@settitle Kisê User Manual
@set MANUAL-REVISION 1
@c @afourpaper
@c end of header

@include version.texi
@include variables.texi


@copying
This manual documents Kisê version @value{VERSION}.

Copyright (C) 2011, 2012, 2013 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end copying


@titlepage
@sp 10
@title Kisê
@subtitle @
  Edition @value{EDITION}, @
  revision @value{MANUAL-REVISION}, @
  for use with Kisê @value{VERSION}
@author The Kisê Developpers

@c the next two commands start the copyright
@page
@vskip 0pt plus 1filll 
@insertcopying
@end titlepage

@ifnottex
@node Top
@top
@end ifnottex


@menu
* Preface::
* Introduction::
* Using Kisê::

Appendices

* GNU Free Documentation License::  The license of this manual.

Indices

* Index::
@end menu


@c insert the table of contents
@contents


@include preface.texi
@include introduction.texi
@include using-kise.texi


@node GNU Free Documentation License
@appendix GNU Free Documentation License

@include fdl.texi


@node Index
@unnumbered Index

@printindex cp

@bye



