@c -*-texinfo-*-
@c This is part of the GNU Foliot User Manual.
@c Copyright (C)  2011 - 2018 Free Software Foundation, Inc.


@node Preface
@unnumbered Preface

This manual describes how to use GNU Foliot.  It relates particularly to
GNU Foliot version @value{VERSION}.

@menu
* Contributors to this manual::
* GNU Foliot License::
@end menu

@node Contributors to this manual
@unnumberedsec Contributors to this Manual

Like GNU Foliot itself, the GNU Foliot user manual is a living
entity. Right now, the contributor to this manual is:

@itemize @bullet
@item David Pirotte
@end itemize

who is also the author and maintainer of GNU Foliot.

You are most welcome to join and help.  Visit GNU Foliot's web site at
@uref{@value{UFOLIOT}} to find out how to get involved.


@node GNU Foliot License
@unnumberedsec The GNU Foliot License
@cindex copying
@cindex GPL
@cindex license

GNU Foliot is Free Software.  GNU Foliot is copyrighted, not public
domain, and there are restrictions on its distribution or
redistribution:

@itemize @bullet
@item
GNU Foliot and supporting files are published under the terms of the GNU
General Public License version 3 or later.  See the file @file{LICENSE}.

@item
This manual is published under the terms of the GNU Free Documentation
License (@pxref{GNU Free Documentation License}).
@end itemize

You must be aware there is no warranty whatsoever for GNU Foliot.  This
is described in full in the license.


@c Local Variables:
@c TeX-master: "foliot.texi"
@c ispell-local-dictionary: "american"
@c End:
