@c -*-texinfo-*-
@c This is part of the GNU Foliot User Manual.
@c Copyright (C)  2011 - 2018 Free Software Foundation, Inc.


@node Using GNU Foliot
@chapter Using GNU Foliot

GNU Foliot User's Manual still is a mock-up: any help is more then
welcome to improve this situation, thanks!

@menu
* Filter criteria::
* Printing dialog::
@end menu


@node Filter criteria
@section Filter criteria

@node Printing dialog
@section Printing dialog

@c The printing dialog is very powerfull. You can choose to print in a
@c pdf file or with a printer.

@c You can define many templates. A template organises how and what to
@c print the entries. To create a new template, clic the + button and
@c change the name in the combo. To delete a template, clic the -
@c button; an alert asks you to confirm the delete. When there is only
@c one model, the - button is disabled.

@c You choose to print only the selected entry or all entries (= all
@c filtered entries).

@c You choose also items to print, group and sort.

@c When an item is grouped, a title will be printed with the content of
@c the item.

@c You can specify, for each item, whether it should be sorted in
@c ascending, descending or unsorted; select the appropriate option.

@c When you check the group box of an item, the print box is also
@c check. The item moves to the top

@c When you clear a print box with group box
