;; -*- mode: org; coding: utf-8 -*-

#+TITLE: kise BUGS file

* Kisê

** Bugs

*** CLOSED [[25] 4] printing a '0.0 hours' [sub]set crashs Kisê
CLOSED: [2011-12-28 Wed 14:47]
- State "CLOSED"     from "OPEN"       [2011-12-28 Wed 14:47]

ktlw/get-totals updated so it will never happen again :)

*** CANCELLED [[24] 3] escape char for LaTeX
CLOSED: [2011-12-19 Mon 10:24]
- State "CANCELLED"  from "OPEN"       [2011-12-19 Mon 10:24] \\
  this is not a bug but a malformed string, scheme wize, which contains
  a single \ instead of \\. this only happens when the string is
  manually written, probably due to a tipo.

in /usr/local/share/guile/alto/2.0/tex/tex.scm

(tex/prep-str-for-tbx-env "date\_" 1 #t)
While reading expression:
ERROR: In procedure scm_lreadr: #<unknown port>:7:34: illegal character in escape sequence: #\_

*** CLOSED [[23] 3] description modifs not saved on filter-* clicked
CLOSED: [2011-11-25 Fri 22:29]
- State "CLOSED"     from "OPEN"       [2011-11-25 Fri 22:29]

while in a filter mode, editing a description [or any other entry],
then clicking filter-clear was the symptom: filter was cleared and the
row reselected, but content added and/or modified was lost. 

kise/on-tv-row-change added on all filter-* button 'clicked signals
as already the case for printing, nav buttons ...

*** OPEN [[22] 3] connect: database's schema incomplete, cancel

When the user try to connect an other database with a
incomplete Kisé schema, he click cancel and then he try to print

*** CLOSED [[21] 3] gui - filter-clear not restoring gui-callback
CLOSED: [2011-11-16 Wed 11:34]
- State "CLOSED"     from "OPEN"       [2011-11-16 Wed 11:34]

of the main interface to [t. Then, user's modification were not saved
neither updated in the store!

*** CLOSED [[20] 3] gui - filechooser: klicking upper left delete window
CLOSED: [2011-11-16 Wed 11:14]
- State "CLOSED"     from "OPEN"       [2011-11-16 Wed 11:14]

button leads to a bug. This already has been corrected in other
dialogs, such as connect -> see c-dialog.scm

*** CLOSED [[19] 3] gui - kc/connect called 2x in create db mode
CLOSED: [2011-10-25 Tue 16:32]
- State "CLOSED"     from "OPEN"       [2011-10-25 Tue 16:32]

for some very obscure reasons, when in 'create' mode, kc/connect is
called 2x x by the number of times connect dialog has been opened and
ok clicked [in creation mode] to avoid these erroneous muliple attemps
to create the same new db, we use the modal characteristic of the
dialog and only performs the code when #t. we should then report a bug
to the gtk and/or guile-gnome list.

*** CANCELLED [[18] 3] gui - duplicate: wrong row is selected
CLOSED: [2011-11-16 Wed 11:35]
- State "CANCELLED"  from "OPEN"       [2011-11-16 Wed 11:35] \\
  This bug was actually later reported as #21: the apparent wrong row
  selection from the user's perspective was actually due to the #21 bug
  which at the time had not yet been identified.

I can not reproduce it so far, but a certain manipulation, which I
can't remember, did show this bug: a wrong database tuple subset or
something like that did cause and probably still causes this
inadequate row selection after duplication in 'some circumstances'

*** OPEN [[17] 3] gui - open-db: clicking 'Ok' while on a folder

should open the folder and not running the open db callback

*** CLOSED [[16] 3] gui - text: charged time of 1 hour writes '1 hours'
CLOSED: [2011-12-03 Sat 19:03]
- State "CLOSED"     from "OPEN"       [2011-12-03 Sat 19:03]

We need to use ngettext anyway, but even before that this simple case
should be corrected.

*** CLOSED [[15] 4] ktlw/delete and duplicate not calling update-totals
CLOSED: [2011-09-11 Sun 19:46] 
- State "CLOSED"     from "OPEN"       [2011-09-11 Sun 19:46]

*** CLOSED [[14] 4] are properly updated after delete
CLOSED: [2011-09-11 Sun 19:47] 
- State "CLOSED"     from "OPEN"       [2011-09-11 Sun 19:47]

Especially when deleting the only record of a selection

*** CLOSED [[13] 4] to-be-charged callback incomplete when active-filter
CLOSED: [2011-09-01 Thu 01:41] 
- State "CLOSED"     from "OPEN"       [2011-09-01 Thu 01:41]

When there is an active filter, 1. without 'to-be-charged, then
clicking one of the checkbox to set one of the record as
to-be-charged, 2. activate the to-be-charged filter condition [then
only one record remains in the list-store, 3. deselect its
to-be-charged field +> crashed the application: this is because both
to-be-charged callback [the details and the list-store] did not add
the id of the tuple to the id-set if and when there was an
active-filter.

*** CLOSED [[12] 4] clicking to-be-charged in the list-store
CLOSED: [2011-09-01 Thu 01:34] 
- State "CLOSED"     from "OPEN"       [2011-09-01 Thu 01:34]

When clicking the checkbox of another row then the active one, the
callback of the checkbox is called before the row-changed! => it is
the previously selected row that is being used and gets updated: both
the database and consequently the charged time / days status bar are
wrong.

ktlw/a-facturer-toggle-set-callback needs to be changed accordingly

*** CLOSED [     4] bad ordering [lacking 'what'] db-kise.scm 
CLOSED: [2011-07-05 Tue 12:20]
- State "CLOSED"       from "OPEN"       [2011-07-05 Tue 12:20]

I did not include 'activity' [what] in the select all ordering clause
but this [obviously] leads to a bad in memory order when several
entries are equal in terms of fields used in the list-store, which
itself leads to wrong gtk entries settings displayed values in the
detailed view.

*** CLOSED [     3] clicking a row does not update the statusbar ratio
CLOSED: [2011-08-04 Thu 17:08] 
- State "CLOSED"       from "OPEN"       [2011-08-04 Thu 17:08]


*** CLOSED [[11] 4] text filters not calling str/prep-str-for-pg
CLOSED: [2011-09-11 Sun 20:13] 
- State "CLOSED"     from "OPEN"       [2011-09-11 Sun 20:13]

*** CLOSED [[10] 4] ktlw/entry-std-cb crashed kise when old-pos was -1
CLOSED: [2011-08-25 Thu 22:52] 
- State "CLOSED"     from "OPEN"  [2011-08-25 Thu 22:53]

*** CLOSED [[9] 4] characters in date filter crashes kise
CLOSED: [2011-08-24 Wed 20:50] 
- State "CLOSED"       from "OPEN"       [2011-08-24 Wed 20:50]

*** CLOSED [[8] 4] alto.br in who and reentering who crashes kise
CLOSED: [2011-08-24 Wed 19:42] 
- State "CLOSED"       from "OPEN"       [2011-08-24 Wed 19:42]

*** CLOSED [[7] 4] a date 'only' [no operator] crashes kise
CLOSED: [2011-08-04 Thu 18:42] 
- State "CLOSED"       from "OPEN"       [2011-08-04 Thu 18:42]

*** CLOSED [[6] 3] ktlw/filter-clear should select previously selected row if possible
CLOSED: [2011-08-23 Tue 18:58] 
- State "CLOSED"       from "OPEN"       [2011-08-23 Tue 18:58]

*** CLOSED [[5] 3] ktlw/filter-apply should select previously selected row if possible
CLOSED: [2011-08-23 Tue 19:15] 
- State "CLOSED"       from "OPEN"       [2011-08-23 Tue 19:15]

*** CLOSED [[4] 3] same filter conditions should not trigger apply-filter
CLOSED: [2011-08-24 Wed 20:50] 
- State "CLOSED"       from "OPEN"       [2011-08-24 Wed 20:50]

*** CLOSED [[3] 3] empty set does not empty entry fields and combo selection
CLOSED: [2011-08-10 Wed 12:05] 
- State "CLOSED"       from "OPEN"       [2011-08-10 Wed 12:05]

*** CLOSED [[2] 3] empty set does not grey inapropriate actions
CLOSED: [2011-08-10 Wed 12:05] 
- State "CLOSED"       from "OPEN"       [2011-08-10 Wed 12:05]

*** CLOSED [[1] 3] empty set - statusbar says 'Record 1/0'
CLOSED: [2011-08-10 Wed 12:05] 
- State "CLOSED"       from "OPEN"       [2011-08-10 Wed 12:05]




** Wishlist

*** NEXT [[0] 1] nothing yet


* Severity levels

** 7 critical
 
makes unrelated software on the system (or the whole system) break, or
causes serious data loss, or introduces a security hole on systems
where you install the package.

** 6 grave

makes the package in question unusable or mostly so, or causes data
loss, or introduces a security hole allowing access to the accounts of
users who use the package.

** 5 serious

is a severe violation of Debian policy (roughly, it violates a "must"
or "required" directive), or, in the package maintainer's or release
manager's opinion, makes the package unsuitable for release.

** 4 important

a bug which has a major effect on the usability of a package, without
rendering it completely unusable to everyone.

** 3 normal

the default value, applicable to most bugs.

** 2 minor

a problem which doesn't affect the package's usefulness, and is
presumably trivial to fix.

** 1 wishlist

for any feature request, and also for any bugs that are very difficult
to fix due to major design considerations.

